name: Release
on: [push]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x.x'
          cache: yarn
      - name: Install dependencies 📦
        run: yarn install 
      - name: Build 🏗
        run: yarn prepare
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Deploy storybook to GitHub Pages
        run: yarn run deploy-storybook -- --ci
        env:
            GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}